name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # || pip3 install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/requirements-dev.txt
      - name: Change directory
        run: |
          cd pyimzml
      - name: Test with pytest and generate report
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
